version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: app_nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: app_mysql
    restart: unless-stopped
    tty: true
    ports:
    - "4306:3306"
    environment:
      MYSQL_DATABASE: laravel_test
      MYSQL_USER: kicin
      MYSQL_PASSWORD: kicin
      MYSQL_ROOT_PASSWORD: kicin
    volumes:
    - ./mysql:/var/lib/mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_php
    volumes:
    - ./src:/var/www
    ports:
    - "9000:9000"
    networks:
      - laravel